syntax = "proto3";
package pb;

option go_package = "github.com/jochem11/go-gql-pg-api/todo/pb";

message Todo {
    string id = 1;
    string text = 2;
    bool completed = 3;
    bytes updatedAt = 4;
}

message PostTodoRequest {
  string text = 1;
  optional bool completed = 2;
}

message PostTodoResponse {
  Todo todo = 1;
}

message GetTodoRequest {
  string id = 1;
}

message GetTodoResponse {
  Todo todo = 1;
}

message GetTodosRequest {}

message GetTodosResponse {
  repeated Todo todos = 1;
}

service TodoService {
  rpc PostTodo(PostTodoRequest) returns (PostTodoResponse) {
  }
  rpc GetTodo(GetTodoRequest) returns (GetTodoResponse) {
  }
  rpc GetTodos(GetTodosRequest) returns (GetTodosResponse) {
  }
}